sudo: required

language: python
python: 2.7

services:
- docker

script:
- python -m doctest build/resolve_jenkins_plugins_dependencies.py
- docker build -t tomdesinto/jenkins-dsl-ready .

after_success:
- >
  [ "$TRAVIS_BRANCH" == "master" ]
  && curl -X POST -H "Content-Type: application/json"
  --data '{"docker_tag_name": "latest"}'
  https://registry.hub.docker.com/u/tomdesinto/jenkins-dsl-ready/trigger/$DOCKER_HUB_TOKEN/